### PR TITLE
Using Translation Strings on PageApprovalStatus

### PR DESCRIPTION
**Pull request by waximabbax**
For: 

https://github.com/ProfessionalWiki/PageApprovals/issues/73

Loading Icon is gonna show for less than a second in most scenarios.

image
image

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Why a loading icon? Is this related to the translations?

**Comment by waximabbax** [comment]
> Why a loading icon? Is this related to the translations?

`Loading...` text was hardcoded so I used a loading icon instead of using translation for this.

**Comment by malberts** [comment]
I think the loading text look better than the icon. Even though it's very quick (but might me slower on a bigger live wiki), it looks a bit more abrupt when the big icon is replaced by text.

https://github.com/ProfessionalWiki/PageApprovals/assets/1428594/204657a4-32a0-46f8-be87-a871a47562a8


https://github.com/ProfessionalWiki/PageApprovals/assets/1428594/c051608a-1e63-40ec-9c66-cf059ead8bf2

**Review by malberts — APPROVED** [review]
The rest of the changes look fine. So if the loading icon is not a problem then we can merge.

**Comment by waximabbax** [comment]
The icon is super small and should load seamlessly; I just wanted to avoid writing a translation for "Loading". I am not sure which one looks better, considering that they are going to show up for a few microseconds; I guess it doesn't matter.

**Comment by JeroenDeDauw** [comment]
Spinners are not great psychologically. In this case you also draw attention to one part of the page that is not there yet. 

In order or worse to better (my opinion ofc):
* Spinner
* `Loading...`
* Do not show anything
* Show a visually similar placeholder

If you agree, then removing the spinner and showing nothing instead should be simple enough.

**Review by JeroenDeDauw — APPROVED** [review]

**Pull request merged**
